file_format: "1"
id: lily58
name: LILY58
type: shield
url: https://github.com/Bastardkb/TBK-Mini
requires: [Nice!Nano]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - lily58_left
  - lily58_right
